services:
  api:
    build:
      context: .
      target: builder
    container_name: dss-api-ie-suricoach-api
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
